name: Node.js Workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm install
      - name: Generate files
        run: npm run update-rss
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: data.json
          path: ./data.json
      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: data.json
